from dataclasses import dataclass, field
from dotenv import load_dotenv
from typing import List
from textwrap import dedent

load_dotenv()  # Cargar variables de entorno desde .env

SECCIONES_TDR = {
    "objetivo_tdr": {
        "definicion": "Esta definición orienta al agente RAG a localizar el OBJETIVO de la convocatoria dentro de los términos de referencia. Busque un párrafo, sección o cuadro que declare explícitamente la finalidad, propósito, meta global o razón de ser del llamado. Los encabezados acostumbrados incluyen “Objetivo de la convocatoria”, “Propósito general”, “Finalidad”, “Objetivo general” o frases afines. El contenido suele describir la problemática que se pretende resolver, el impacto esperado, los beneficiarios y la contribución al desarrollo científico, tecnológico o de innovación. También puede incorporar objetivos específicos, aunque el núcleo será un enunciado claro, medible y alineado con la política pública o la estrategia institucional de la entidad financiadora. Señales contextuales: aparece normalmente en las primeras dos páginas, tras la introducción, acompañado de verbos en infinitivo como “promover”, “fortalecer”, “financiar”, “estimular”, “apoyar”, “impulsar”, “consolidar” o “fomentar”. Incluye a veces indicadores clave (p. ej., número de proyectos, montos, regiones o áreas prioritarias) y vincula las líneas temáticas o demandas territoriales. El agente debe extraer el texto completo y descartar apartados posteriores. Esta guía enfatiza diferenciar la declaración central de cualquier nota aclaratoria, relevancia pertinencia alineación elegibilidad contexto resultado impacto cobertura financiación modalidad región sector institucional obligatorio opcional guía detallada descripción."
        },
    "dirigida_a_tdr": {
        "definicion": "Esta definición ayuda al agente RAG a ubicar la sección que especifica a QUIÉN va dirigida la convocatoria, incluyendo tipos de entidades participantes, naturaleza jurídica y requisitos institucionales. Busque encabezados como “Dirigida a”, “Destinatarios”, “Población objetivo”, “Entidades elegibles”, “Beneficiarios” o “Quiénes pueden participar”. El pasaje suele enumerar universidades, centros de I+D, empresas, pymes, gremios, entidades públicas, ONG o alianzas estratégicas, indicando si deben estar constituidas legalmente, tener experiencia, registro o certificaciones. Pueden aparecer sub-categorías (“rol líder”, “co-ejecutor”, “aliado”) y condiciones de ubicación territorial, sector económico, nivel tecnológico o capacidad instalada. Palabras clave: “personería jurídica”, “NIT”, “SNIES”, “Minciencias”, “grupos categorizados”, “centros de desarrollo tecnológico”, “empresas ancla”. Normalmente se encuentra después del objetivo y antes de los requisitos técnicos. La sección a veces contiene tablas comparativas de roles y porcentajes de participación. El agente debe extraer el texto completo y reconocer sinónimos de entidades (instituciones, organizaciones, actores, postulantes, proponentes), evitando confusión con requisitos de proyecto o criterios de evaluación. Detecte verbos “podrán participar”, “deberán ser”, “están invitados”, “deben pertenecer”, “aplica a”. Relevancia pertinencia alineación elegibilidad contexto resultado impacto cobertura financiación modalidad región sector institucional obligatorio opcional guía detallada descripción sección localización documento referencia indicador clave búsqueda extracción sintaxis."
        },
    "demandas_territoriales_tdr": {
        "definicion":"Esta definición orienta al agente RAG a encontrar la parte donde se describen las DEMANDAS TERRITORIALES o retos regionales priorizados. Busque títulos como “Demandas territoriales”, “Retos locales”, “Problemáticas regionales”, “Prioridades territoriales”, “Desafíos departamentales” o “Enfoque regional”. El contenido lista necesidades identificadas por gobernaciones, alcaldías, clústeres o comunidades, expresadas en sectores estratégicos (salud, energía, agro, ambiente, TIC, manufactura). Suele incluir tablas que vinculan código del territorio, descripción del reto, línea temática asociada y entidad demandante. Palabras clave: “territorio”, “departamento”, “región”, “municipio”, “agenda regional”, “reto”, “necesidad”, “problema”. Puede presentarse como anexo o dentro del cuerpo principal. El agente debe capturar la lista completa para luego filtrar o cruzar con capacidades institucionales. Señales: referencia a mapas, códigos DANE, montos de cofinanciación diferenciados por región; verbos “priorizar”, “resolver”, “atender”, “abordar”, “cerrar brechas”. Distinguir esta sección de líneas temáticas generales, pues su énfasis es geográfico y no disciplinar. Incluye a menudo un resumen de contexto socioeconómico regional. Relevancia pertinencia alineación elegibilidad contexto resultado impacto cobertura financiación modalidad región sector institucional obligatorio opcional guía detallada descripción sección localización documento referencia indicador clave búsqueda extracción sintaxis palabra término encabezado subtítulo apartado."
        },
    "lineas_tematicas_tdr": {
        "definicion": "Esta definición indica al agente RAG cómo detectar la sección de LÍNEAS TEMÁTICAS o áreas de conocimiento financiables. Busque encabezados “Líneas temáticas”, “Áreas estratégicas”, “Campos de investigación”, “Temáticas priorizadas”, “Sectores foco” o “Ámbitos de aplicación”. El fragmento enumera disciplinas, verticales tecnológicas o problemáticas sectoriales ligadas a la política pública. Suele presentar códigos OCDE, SNCTI o UNESCO, así como descriptores MeSH o palabras clave. Puede aparecer como lista numerada, tabla con códigos o matriz que cruce líneas y demandas territoriales. Claves léxicas: “ciencia básica”, “biotecnología”, “energías renovables”, “transformación digital”, “salud”, “agroindustria”, “industria 4.0”. A veces incluye justificación breve, objetivos específicos por línea y reglas de coherencia temática. Se ubica habitualmente después de los objetivos y antes del alcance. El agente debe extraer cada línea con descripción, código y restricciones, ignorando ejemplos externos. Observe verbos “comprende”, “abarca”, “incluye”, “contempla” y referencias normativas. Relevancia pertinencia alineación elegibilidad contexto resultado impacto cobertura financiación modalidad región sector institucional obligatorio opcional guía detallada descripción sección localización documento referencia indicador clave búsqueda extracción sintaxis palabra término encabezado subtítulo apartado texto principal secundario completo preciso inequívoco."
        },
    "alcance_convocatoria_tdr": {
        "definicion": "Esta descripción ayuda al agente RAG a identificar el ALCANCE de la convocatoria, es decir, los límites, cobertura y dimensiones de lo que se financiará. Busque secciones tituladas “Alcance”, “Cobertura”, “Objeto de la convocatoria”, “Qué se financia” o “Componentes financiables”. El contenido delimita fases (investigación aplicada, desarrollo experimental, validación, escalamiento), actividades subvencionables (recursos humanos, equipamiento, servicios) y niveles de madurez tecnológica (TRL). También define duración máxima, valor financiado, porcentaje de cofinanciación y población beneficiaria. Palabras clave: “comprende”, “incluye”, “excluye”, “no se financiarán”, “límites”, “se admiten”. Puede contener cuadros de rubros elegibles/ineligibles y diagramas de flujo. Normalmente aparece tras las líneas temáticas. El agente debe tomar el texto íntegro y distinguirlo de requisitos administrativos. Señales: referencias normativas, tablas de financiación por actividad, menciones a partidas presupuestales; verbos negativos “no se reconocerán”, “no cubre”. Relevancia pertinencia alineación elegibilidad contexto resultado impacto cobertura financiación modalidad región sector institucional obligatorio opcional guía detallada descripción sección localización documento referencia indicador clave búsqueda extracción sintaxis palabra término encabezado subtítulo apartado texto principal secundario completo preciso inequívoco normativo estándar formato plantilla."
        },
    "orientaciones_vinculacion_talento_humano_tdr": {
        "definicion": "Esta definición permite al agente RAG localizar las ORIENTACIONES PARA VINCULACIÓN DE TALENTO HUMANO, apartado que describe roles, perfiles y modalidades contractuales financiables. Busque títulos “Vinculación de talento humano”, “Participación de investigadores”, “Pagos de personal”, “Equipo de trabajo”, “Recursos humanos”, “Becarios”, “Jóvenes investigadores”. La sección detalla elegibilidad de investigadores principales y coinvestigadores, requisitos de formación, experiencia, dedicación mínima, salarios o estipendios, categorías salariales, becas, topes de financiación y obligaciones de permanencia. Incluye modalidades de contratación (OPS, vinculación laboral, pasantías) y limitaciones de doble financiación. Palabras clave: “honorarios”, “asignación”, “contratación”, “perfil”, “dedicación”, “semillero”, “mentor”. Puede aparecer tabla con rangos salariales y anexos de hoja de vida. Ubicación usual: después del alcance o dentro del presupuesto elegible. El agente debe extraer la totalidad para validar costos de personal. Verbos guía: “podrán vincularse”, “deberán contar”, “se financiará”. Relevancia pertinencia alineación elegibilidad contexto resultado impacto cobertura financiación modalidad región sector institucional obligatorio opcional guía detallada descripción sección localización documento referencia indicador clave búsqueda extracción sintaxis palabra término encabezado subtítulo apartado texto principal secundario completo preciso inequívoco."
        },
    "requisitos_proyecto_tdr": {
        "definicion": "Esta definición guía al agente RAG a encontrar los REQUISITOS DEL PROYECTO para postularse. Busque encabezados “Requisitos de participación”, “Condiciones de elegibilidad”, “Requisitos del proyecto”, “Condiciones mínimas”, “Criterios habilitantes”, “Documentación requerida”. El apartado lista condiciones técnicas, administrativas y financieras: formato de propuesta, aval institucional, cartas de compromiso, cofinanciación mínima, certificados de existencia, categorización de grupo, experiencia previa, propiedad intelectual y aval ético. También define topes presupuestales, cronograma, idioma, firma digital y fecha límite. Palabras clave: “indispensable”, “obligatorio”, “debe”, “requiere”, “adjuntar”, “cumplir”. A menudo incluye tabla de chequeo. Se posiciona antes de criterios de evaluación. El agente debe extraer completo para construir un validador de requisitos. Señales: referencias a “Formato A”, “Anexo 2”, “link de cargue”, “SECOP II”. Distinguir de contenido del proyecto, que describe estructura metodológica. Relevancia pertinencia alineación elegibilidad contexto resultado impacto cobertura financiación modalidad región sector institucional obligatorio opcional guía detallada descripción sección localización documento referencia indicador clave búsqueda extracción sintaxis palabra término encabezado subtítulo apartado texto principal secundario completo preciso inequívoco estándar formato plantilla anexo tabla lista numerada reiteración."
        },
    "contenido_proyecto_tdr": {
        "definicion": "Esta definición facilita que el agente RAG identifique el CONTENIDO DEL PROYECTO exigido. Busque títulos “Contenido de la propuesta”, “Estructura del proyecto”, “Documento técnico”, “Componentes del proyecto”, “Formato de presentación”, “Plan de trabajo”. La sección detalla capítulos obligatorios: resumen ejecutivo, justificación, marco teórico, objetivos, metodología, plan de actividades, cronograma, presupuesto, riesgos, indicadores, impacto, sostenibilidad y transferencia. Puede anexar plantillas o instructivos. Palabras clave: “deberá incluir”, “sección”, “capítulo”, “apartado”, “extensión”, “formato”. Incluye normas de estilo (tipo de letra, páginas) y enlaces de descarga. Ubicación: después de requisitos y antes de evaluación. El agente debe extraer lista estructurada con orden, título, descripción y número de páginas. Señales: íconos de documento, referencia a “Anexo 3” o “Formulario en línea”. Distinguir de criterios de evaluación que puntúan el contenido. Relevancia pertinencia alineación elegibilidad contexto resultado impacto cobertura financiación modalidad región sector institucional obligatorio opcional guía detallada descripción sección localización documento referencia indicador clave búsqueda extracción sintaxis palabra término encabezado subtítulo apartado texto principal secundario completo preciso inequívoco normativo estándar formato plantilla anexo tabla lista."
        },
    "duracion_financiacion_tdr": {
        "definicion": "Esta definición permite al agente RAG ubicar la sección sobre DURACIÓN Y FINANCIACIÓN de los proyectos. Busque encabezados “Duración y financiación”, “Plazo de ejecución”, “Monto de financiación”, “Tiempo máximo de ejecución”, “Recursos disponibles”, “Bolsa de recursos”. El apartado especifica meses o años de ejecución, prórrogas permitidas, fases, desembolsos por hitos, cofinanciación requerida e inversión mínima por entidad. Palabras clave: “meses”, “años”, “vigencia”, “desembolso”, “aporte”, “contrapartida”, “tope”, “valor total”, “costo elegible”. Suele incluir tablas por línea temática o territorio y explicar mecanismos de giro (anticipo, contra-reembolso, entrega por resultados). También detalla el cronograma de reporte financiero. Ubicación típica: cerca de requisitos presupuestales o al final. El agente debe extraer la totalidad para crear calculadora de viabilidad financiera. Verbos: “otorgará”, “asignará”, “cubrirá”, “deberá aportar”, “podrá financiar”. Distinga de alcance, que trata de actividades elegibles, y de criterios de evaluación, que puntúan uso de recursos. Relevancia pertinencia alineación elegibilidad contexto resultado impacto cobertura financiación modalidad región sector institucional obligatorio opcional guía detallada descripción sección localización documento referencia indicador clave búsqueda extracción sintaxis palabra término encabezado subtítulo apartado texto principal secundario completo preciso inequívoco."
        },
    "criterios_evaluacion_proyectos_tdr": {
        "definicion": "Esta definición indica al agente RAG cómo localizar los CRITERIOS DE EVALUACIÓN. Busque encabezados “Criterios de evaluación”, “Valoración de propuestas”, “Puntajes”, “Baremo”, “Tabla de puntuación”, “Forma de evaluación”. La sección presenta factores y porcentajes: pertinencia, coherencia, metodología, impacto, capacidad del equipo, viabilidad financiera, alineación temática, sostenibilidad, articulación territorial y riesgos. Incluye escalas numéricas, rangos de puntaje, umbrales mínimos y fórmulas de calificación. Palabras clave: “porcentaje”, “puntaje”, “subcriterio”, “máximo”, “mínimo”, “evaluador”, “calificación”. Puede describir proceso de doble ciego, etapas (habilitación, técnica, financiera) y órganos (pares académicos, comité técnico). Ubicación: normalmente después del contenido del proyecto o en un anexo. El agente debe extraer tabla completa con pesos y descriptores para alimentar modelos de scoring. Señales: colores en tabla, notas al pie con fórmulas, referencias a normas; verbos “será evaluado”, “otorgará”, “asigna”, “pondera”. Diferenciar de requisitos habilitantes, que son excluyentes, y de alcance, que define límites de financiamiento. Relevancia pertinencia alineación elegibilidad contexto resultado impacto cobertura financiación modalidad región sector institucional obligatorio opcional guía detallada descripción sección localización documento referencia indicador clave búsqueda extracción sintaxis palabra término encabezado subtítulo apartado texto principal secundario completo preciso inequívoco."
        },
}

@dataclass(kw_only=True)
class MultiAgentConfiguration:
    """Configurable fields for the multi-agent system."""
    gpt4omini: str = "gpt-4o-mini"
    gpt4o: str = "gpt-4o"
    o3mini: str = "o3-mini"
    o4mini: str = "o4-mini"
    gpt41mini: str = "gpt-4.1-mini"
    gemini2flash: str = "gemini-2.0-flash-lite"
    embedding_model: str = "text-embedding-3-small"
    base_consistency_score: int = 10
    objetivo_tdr: List = field(default_factory=lambda: [SECCIONES_TDR["objetivo_tdr"]])
    dirigida_a_tdr: List = field(default_factory=lambda: [SECCIONES_TDR["dirigida_a_tdr"]])
    demandas_territoriales_tdr: List = field(default_factory=lambda: [SECCIONES_TDR["demandas_territoriales_tdr"]])
    lineas_tematicas_tdr: List = field(default_factory=lambda: [SECCIONES_TDR["lineas_tematicas_tdr"]])
    alcance_convocatoria_tdr: List = field(default_factory=lambda: [SECCIONES_TDR["alcance_convocatoria_tdr"]])
    requisitos_proyecto_tdr: List = field(default_factory=lambda: [SECCIONES_TDR["requisitos_proyecto_tdr"]])
    contenido_proyecto_tdr: List = field(default_factory=lambda: [SECCIONES_TDR["contenido_proyecto_tdr"]])
    duracion_financiacion_tdr: List = field(default_factory=lambda: [SECCIONES_TDR["duracion_financiacion_tdr"]])
    criterios_evaluacion_proyectos_tdr: List = field(default_factory=lambda: [SECCIONES_TDR["criterios_evaluacion_proyectos_tdr"]])
    
    @classmethod
    def from_runnable_config(cls, config):
        """Convierte un RunnableConfig en una instancia de Configuration"""
        configurable_for_agents = config.configurable if hasattr(config, "configurable") else {}
        return cls(**configurable_for_agents)